version: '3.5'
services:
  develop:
      build: ./develop
      restart: always
      hostname: foo
      privileged: true
      command: ["sh", "-c", "tail -f /dev/null"]
      environment:
        GO111MODULE: "on"
        GOPROXY: "https://goproxy.io"
        CGO_ENABLED: 0
        PROBE_TARGET_SOURCE_URL: "http://test-mib-config.hk.ufileos.com/network-probe-targets"
        PROBE_CLIENT_ID: "test"
      volumes:
        - ./src:/work/src
        - ./produce/bin:/work/bin
        - "syslogunixsocket:/dev/syslog"
      cap_add:
        - ALL
  develop-rsyslog-agent:
      image: xgoteam/rsyslog:centos7
      restart: always
      privileged: true
      command: ["/usr/sbin/rsyslogd", "-dn"]
      networks:
        default:
          aliases:
            - rsyslog-agent
      volumes:
        - "syslogunixsocket:/dev/syslog"
        - ./etc/rsyslog-agent.conf:/etc/rsyslog.conf
  develop-rsyslog-server:
      image: xgoteam/rsyslog:centos7
      restart: always
      privileged: true
      command: ["/usr/sbin/rsyslogd", "-dn"]
      networks:
        default:
          aliases:
            - rsyslog
      volumes:
        - ./etc/rsyslog-server.conf:/etc/rsyslog.conf
volumes:
  syslogunixsocket: