version: '3.5'
services:
  produce:
      # build: ./produce
      image: tomhjx/network-probe:latest
      restart: always
      privileged: true
      command: ["sh", "-c", "/app/bin/service"]
      environment:
        PROBE_INTERVAL_SECOND: 30
        TARGET_SOURCE_URL: "http://test-mib-config.hk.ufileos.com/network-probe-targets"
      volumes:
        - ./log:/app/log/
      cap_add:
        - ALL